name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Your issue has been issued! That was your first, the organisation(my repository) thanks you dearly for the contribution! All I can say is, for you and I -- for reliability reasons, ofc -- is that hopefully we don't have to re-visit this convo! Till we meet again =)"
        pr-message: "Ziiing! Congrats on a successful repo pull -- have fun with the source code! For any maverick ideas, please adhere to the licenscing agreement listed."
